---

# perform the rest of the install

- hosts: debian-virtual  # change if needed - see note above
  gather_facts: no

  become: yes

  tasks:

  - name: lock root (so it can't get up to mischief)
    command: usermod -L root

  - name: committing the root user lock to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'locking the root user'; fi"

  - name: turn on periodic apt updates and autocleaning
    copy: dest=/etc/apt/apt.conf.d/02periodic
          src=etc/apt/apt.conf.d/02periodic
          owner=root
          group=root
          mode=0644

  - name: committing the apt config change to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'enabling periodic updates for apt'; fi"

  - name: enable the mozilla firefox release repo
    copy: dest=/etc/apt/sources.list.d/firefox-release.list
          src=etc/apt/sources.list.d/firefox-release.list
          owner=root
          group=root
          mode=0644

  - name: install the mozilla key
    apt_key: url=http://mozilla.debian.net/archive.asc

  - name: committing the sources.list change to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'enabling the firefox-release repo'; fi"

  - name: enable the backports repo
    copy: dest=/etc/apt/sources.list.d/jessie-backports.list
          src=etc/apt/sources.list.d/jessie-backports.list
          owner=root
          group=root
          mode=0644

  - name: committing the jessie-backports.list change to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'enabling the jessie-backports repo'; fi"

  - name: swapping ctrl and caps
    patch: >
      src=etc/default/keyboard.patch
      dest=/etc/default/keyboard

  - name: committing the swap caps ctrl change to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'swapping caps and ctrl'; fi"

  - name: install any pending upgrades (and update the cache with the new repos)
    apt: update_cache=yes upgrade=full

  - name: retrieve recommended packages that aren't installed
    shell: aptitude search '~RBrecommends:~i' | cut -f4 -d' '
    register: packages

  - name: install missing recommended packages, marking auto
    command: aptitude -y install {{ item }}+M
    with_items: "{{ packages.stdout_lines }}"

  # thinkpad specific stuff

  - name: install tp_smapi kernel module
    apt: name=tp-smapi-dkms

  # command line utils

  - name: install cli utilities
    apt: name={{ item }}
    with_items:
    - ntp
    - udisks2
    - udevil
    - apparmor-profiles
    - apparmor-profiles-extra
    - ufw

  - name: updating grub defaults for app armor
    patch: >
      src=etc/default/grub.patch
      dest=/etc/default/grub

  - name: committing the app armor grub changes to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'enabling app armor'; fi"

  - name: update grub, since we updated the defaults
    command: update-grub

  - name: configure ufw
    ufw: rule=allow name=OpenSSH

  - name: enable ufw
    ufw: state=enabled

  - name: committing the ufw changes to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'config and enable ufw'; fi"

  # GUI

  - name: install the desktop environment
    apt: name={{ item }}
    with_items:
    - rxvt-unicode-256color
    - xorg
    - i3
    - lightdm
    - wicd-gtk
    - pulseaudio
    - xautolock
    - gtk-redshift
    - fonts-inconsolata

  - name: install firefox
    apt: name=firefox default_release=jessie-backports

  - name: install pidgin
    apt: name={{ item }}
    with_items:
    - pidgin
    - pidgin-libnotify
    - pidgin-otr
    - pidgin-twitter

  - name: install emacs
    apt: name={{ item }} default_release=jessie-backports
    with_items:
    - emacs24-common-non-dfsg
    - emacs24
