---

# perform the rest of the install

- hosts: debian-virtual  # change if needed - see note above
  gather_facts: no

  become: yes

  tasks:

  - name: lock root (so it can't get up to mischief)
    command: usermod -L root

  - name: committing the root user lock to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'locking the root user'; fi"

  - name: add the ansible_user to the dialout group (needed for chirp)
    user: name={{ ansible_user }} append=yes groups=sudo

  - name: committing the group change to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'adding {{ ansible_user }} to the dialout group'; fi"

  - name: turn on periodic apt updates and autocleaning
    copy: dest=/etc/apt/apt.conf.d/02periodic
          src=etc/apt/apt.conf.d/02periodic
          owner=root
          group=root
          mode=0644

  - name: committing the apt config change to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'enabling periodic updates for apt'; fi"

  - name: update crypttab to pass discards
    crypttab: name=sda5_crypt
              opts=discard
              state=opts_present

  - name: update initramfs with new crypttab option
    command: update-initramfs -u -k all

  - name: link weekly TRIM for SSD (service)
    file: src=/usr/share/doc/util-linux/examples/fstrim.service
          dest=/etc/systemd/system/fstrim.service
          state=link

  # this file is copied and not linked because systemd won't let you
  # enable a symlink... there are probably good reasons, but this is
  # really annoying
  - name: copy weekly TRIM for SSD (timer)
    copy: src=/usr/share/doc/util-linux/examples/fstrim.timer
          dest=/etc/systemd/system/fstrim.timer
          remote_src=true

  - name: enable weekly TRIM for SSD
    systemd: name=fstrim.timer
             enabled=yes

  - name: committing the TRIM changes to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'enabling weekly TRIM for SSD'; fi"

  - name: install the HTTPS transport for apt
    apt: name=apt-transport-https

  # TODO: this appears to be broken - we probably need to disable and use ESR
  - name: enable the mozilla firefox release repo
    copy: dest=/etc/apt/sources.list.d/firefox-release.list
          src=etc/apt/sources.list.d/firefox-release.list
          owner=root
          group=root
          mode=0644

  - name: install the mozilla key
    apt_key: url=https://mozilla.debian.net/archive.asc

  - name: committing the sources.list change to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'enabling the firefox-release repo'; fi"

  # add the skype key: https://repo.skype.com/data/SKYPE-GPG-KEY
  # add the skype repo: etc/apt/sources.list.d/skype-stable.list
  # also install skypeforlinux below

  # also add the ubiquiti repo
  # https://help.ubnt.com/hc/en-us/articles/220066768-UniFi-How-to-Install-Update-via-APT-on-Debian-or-Ubuntu

  # TODO: change this to stretch!
  - name: enable the backports repo
    copy: dest=/etc/apt/sources.list.d/jessie-backports.list
          src=etc/apt/sources.list.d/jessie-backports.list
          owner=root
          group=root
          mode=0644

  - name: committing the jessie-backports.list change to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'enabling the jessie-backports repo'; fi"

  - name: swapping ctrl and caps
    patch: >
      src=etc/default/keyboard.patch
      dest=/etc/default/keyboard

  - name: committing the swap caps ctrl change to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'swapping caps and ctrl'; fi"

  - name: install any pending upgrades (and update the cache with the new repos)
    apt: update_cache=yes upgrade=full

  # TODO: requires aptitude, but it's not installed by default anymore!
  - name: retrieve recommended packages that aren't installed
    shell: aptitude search '~RBrecommends:~i' | cut -f3 -d' '
    register: packages

  - name: install missing recommended packages, marking auto
    command: aptitude -y install {{ item }}+M
    with_items: "{{ packages.stdout_lines }}"

  # Open firmware for USB NIC (using until BIOS can be flashed)

  - name: install htc_9271.fw (ath)
    copy: dest=/lib/firmware/htc_9271.fw
          src=lib/firmware/htc_9271.fw
          owner=root
          group=root
          mode=0644

  # thinkpad specific stuff

  - name: install tp_smapi kernel module
    apt: name=tp-smapi-dkms

  # power management

  - name: install tlp
    apt: name=tlp

  # ntp (via systemd)

  # TODO: this patch is broken and maybe unneeded
  - name: enable time servers
    patch: >
      src=etc/systemd/timesyncd.conf.patch
      dest=/etc/systemd/timesyncd.conf

  - name: enable ntp
    command: timedatectl set-ntp true

  - name: committing ntp changes to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'config and enable ntp'; fi"

  # command line utils

  - name: install cli utilities
    apt: name={{ item }}
    with_items:
    - apparmor-profiles
    - apparmor-profiles-extra
    - ufw
    - needrestart
    - stow
    - curl
    - dnsutils
    - whois
    - adb  # for android development

  - name: updating grub defaults for app armor
    patch: >
      src=etc/default/grub.patch
      dest=/etc/default/grub

  - name: committing the app armor grub changes to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'enabling app armor'; fi"

  - name: update grub, since we updated the defaults
    command: update-grub

  - name: configure ufw
    ufw: rule=allow name=OpenSSH

  - name: enable ufw
    ufw: state=enabled

  - name: committing the ufw changes to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'config and enable ufw'; fi"

  # GUI

  - name: install the desktop environment
    apt: name={{ item }}
    with_items:
    - rxvt-unicode-256color
    - xorg
    - i3
    - lightdm
    - network-manager-gnome
    - pavucontrol  # includes pulseaudio
    - xautolock
    - gtk-redshift
    - fonts-inconsolata
    - fonts-liberation
    - xcalib
    - gnome-screenshot  # doesn't depend on gnome, oddly
    - gimp
    - xclip  # command line tool for interacting with the clipboard
    - chromium  # needed for dev work
    - chirp
    - corebird  # twitter
    - nautilus-dropbox  # until I can switch over to syncthing
    - freerdp-x11

  - name: install firefox
    apt: name=firefox default_release=jessie-backports

  - name: install pidgin
    apt: name={{ item }}
    with_items:
    - pidgin
    - pidgin-libnotify
    - pidgin-otr

  - name: install emacs
    apt: name={{ item }}
    with_items:
    - emacs25-common-non-dfsg
    - emacs25
    - install-info

  - name: update info index
    command: update-info-dir

  # Build Dependencies

  - name: python build dependencies (for pyenv)
    apt: name={{ item }}
    with_items:
    - build-essential
    - libbz2-dev
    - libdb-dev
    - libffi-dev
    - libgdbm-dev
    - liblzma-dev
    - libncursesw5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - tk-dev
    - zlib1g-dev

  # Python Utilities (needed for pyenv)
  - name: python utilities (for pyenv)
    apt: name={{ item }}
    with_items:
    - python-pip
    - python-virtualenv
