---

# setup etckeeper and sudo and then grant the remote user sudo access

# this host is expected to have a few characteristics so that this all works:
# - ansible_user is set for the host
# - the ansible_user and root have the same password (root is locked early on)

- hosts: debian-virtual
  gather_facts: no

  become: yes
  become_method: su

  tasks:

  - name: install etckeeper and update the package cache (installs git as well)
    apt: update_cache=yes name=etckeeper

  # this is a separate install because we want etckeeper to pick it up

  - name: install sudo
    apt: name=sudo

  - name: add the ansible_user to the sudo group
    user: name={{ ansible_user }} append=yes groups=sudo

  - name: committing the group change to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'adding {{ ansible_user }} to the sudo group'; fi"

# perform the rest of the install

- hosts: debian-virtual  # change if needed - see note above
  gather_facts: no

  become: yes

  tasks:

  - name: lock root (so it can't get up to mischief)
    command: usermod -L root

  - name: committing the root user lock to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'locking the root user'; fi"

  - name: turn on periodic apt updates and autocleaning
    copy: dest=/etc/apt/apt.conf.d/02periodic
          src=etc/apt/apt.conf.d/02periodic
          owner=root
          group=root
          mode=0644

  - name: committing the apt config change to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'enabling periodic updates for apt'; fi"

  - name: enable the mozilla iceweasel release repo
    copy: dest=/etc/apt/sources.list.d/iceweasel-release.list
          src=etc/apt/sources.list.d/iceweasel-release.list
          owner=root
          group=root
          mode=0644

  - name: install the mozilla key
    apt_key: url=http://mozilla.debian.net/archive.asc

  - name: committing the sources.list change to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'enabling the iceweasel-release repo'; fi"

  - name: enable the unstable repo
    copy: dest=/etc/apt/sources.list.d/unstable.list
          src=etc/apt/sources.list.d/unstable.list
          owner=root
          group=root
          mode=0644

  - name: make sure unstable packages are never installed unless we ask specifically
    copy: dest=/etc/apt/preferences.d/prevent-unstable
          src=etc/apt/preferences.d/prevent-unstable
          owner=root
          group=root
          mode=0644

  - name: committing the unstable repo change to etckeeper
    shell: "if etckeeper unclean;
            then etckeeper commit 'enabling the unstable repo'; fi"

  - name: install any pending upgrades (and update the cache with the new repos)
    apt: update_cache=yes upgrade=full

  - name: retrieve recommended packages that aren't installed
    shell: aptitude search '~RBrecommends:~i' | cut -f4 -d' '
    register: packages

  - name: install missing recommended packages, marking auto
    command: aptitude -y install {{ item }}+M
    with_items: "{{ packages.stdout_lines }}"

  # thinkpad specific stuff

  - name: create bluetooth firmware path
    file: path=/lib/firmware/brcm
          owner=root
          group=root
          mode=0755
          state=directory

  - name: install the bluetooth firmware
    copy: dest=/lib/firmware/brcm/BCM20702A0-0a5c-21e6.hcd
          src=lib/firmware/brcm/BCM20702A0-0a5c-21e6.hcd
          owner=root
          group=root
          mode=0644

  - name: install tp_smapi kernel module
    apt: name=tp-smapi-dkms

  # command line utils

  - name: install basic utilities
    apt: name={{ item }}
    with_items:
    - ntp
    - ufw

  - name: configure ufw
    ufw: rule=allow name=OpenSSH

  - name: enable ufw
    ufw: state=enabled

  - name: committing the ufw changes to etckeeper
    command: "etckeeper commit 'config and enable ufw'"
    ignore_errors: yes

  # GUI

  - name: install the desktop environment
    apt: name={{ item }}
    with_items:
    - xorg
    - i3
    - lightdm
    - network-manager-gnome
    - pulseaudio
    - xautolock
    - gtk-redshift

  - name: install iceweasel
    apt: name=iceweasel default_release=jessie-backports

  - name: install pidgin
    apt: name={{ item }}
    with_items:
    - pidgin
    - pidgin-libnotify
    - pidgin-otr
    - pidgin-twitter

  # annoyingly, apt doesn't support the /distro syntax (only the -t distro syntax)

  - name: install emacs (from unstable)
    command: aptitude -y install {{ item }}
    with_items:
    - emacs24-common/unstable
    - emacs24-common-non-dfsg/unstable
    - emacs24-el/unstable
    - emacs24-bin-common/unstable
    - emacs24/unstable
