---
- hosts: debian-virtual  # set this if needed!
  gather_facts: no

  vars:
    remote_user: artlogic  # set this if needed!

  remote_user: "{{ remote_user }}"
  become: yes
  become_method: su

  tasks:

  - name: install etckeeper and update the package cache (installs git as well)
    apt: update_cache=yes name=etckeeper

  - name: add the remote_user to the sudo group
    user: name={{ remote_user }} append=yes groups=sudo

  - name: committing the group change to etckeeper
    command: "etckeeper commit 'adding {{ remote_user }} to the sudo group'"

  - name: turn on periodic apt updates and autocleaning
    copy: dest=/etc/apt/apt.conf.d/02periodic
          src=etc/apt/apt.conf.d/02periodic
          owner=root
          group=root
          mode=0644

  - name: committing the apt config change to etckeeper
    command: "etckeeper commit 'enabling periodic updates for apt'"

  - name: enable the mozilla iceweasel release repo
    copy: dest=/etc/apt/sources.list.d/iceweasel-release.list
          src=etc/apt/sources.list.d/iceweasel-release.list
          owner=root
          group=root
          mode=0644

  - name: install the mozilla key
    apt_key: url=http://mozilla.debian.net/archive.asc

  - name: committing the sources.list change to etckeeper
    command: "etckeeper commit 'enabling the iceweasel-release repo'"

  - name: install any pending upgrades (and update the cache with the new repos)
    apt: update_cache=yes upgrade=full

  - name: retrieve recommended packages that aren't installed
    shell: aptitude search '~RBrecommends:~i' | cut -f4 -d' '
    register: packages

  - name: install missing recommended packages, marking auto
    command: aptitude -y install {{ item }}+M
    with_items: "{{ packages.stdout_lines }}"

  # thinkpad specific stuff

  - name: create bluetooth firmware path
    file: path=/lib/firmware/brcm
          owner=root
          group=root
          mode=0755
          state=directory

  - name: install the bluetooth firmware
    copy: dest=/lib/firmware/brcm/BCM20702A0-0a5c-21e6.hcd
          src=lib/firmware/brcm/BCM20702A0-0a5c-21e6.hcd
          owner=root
          group=root
          mode=0644

  - name: install tp_smapi kernel module
    apt: name=tp-smapi-dkms

  # command line utils

  - name: install basic utilities
    apt: name={{ item }}
    with_items:
    - ntp
    - sudo
    - ufw

  - name: lock root (so it can't get up to mischief)
    command: usermod -L root

  - name: committing the root user lock to etckeeper
    command: "etckeeper commit 'locking the root user'"

  - name: configure ufw
    ufw: rule=allow name=OpenSSH

  - name: enable ufw
    ufw: state=enabled

  - name: committing the ufw changes to etckeeper
    command: "etckeeper commit 'config and enable ufw'"

  # GUI

  - name: install the desktop environment
    apt: name={{ item }}
    with_items:
    - xorg
    - i3
    - lightdm
    - network-manager-gnome

  - name: install iceweasel
    apt: name=iceweasel default_release=jessie-backports
